# Generated by Django 4.1 on 2022-09-07 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMt5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.IntegerField(verbose_name='Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('server', models.CharField(max_length=30, verbose_name='Servidor')),
                ('status', models.CharField(choices=[('0', 'Desconectado'), ('1', 'Conectado'), ('2', 'Error')], max_length=1, verbose_name='Estado')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha Inicial')),
                ('end_date', models.DateField(verbose_name='Fecha Final')),
                ('start_balance', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Balance Inicial')),
                ('withdraw_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Retiro/Deposito')),
                ('end_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Balance Final')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Ganancia Bruta')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Ganancia Neta')),
                ('id_account_mt5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps.accountmt5')),
            ],
        ),
    ]
