# Generated by Django 4.1.1 on 2022-10-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmt5',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
