# Generated by Django 4.1.4 on 2023-01-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmt5',
            name='reconnect',
            field=models.BooleanField(default=True, verbose_name='Reconexión hablitada'),
            preserve_default=False,
        ),
    ]
