# Generated by Django 4.1.2 on 2023-01-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0002_accountmt5_reconnect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmt5',
            options={'verbose_name_plural': 'Accounts mt5'},
        ),
    ]
