# Generated by Django 4.1.1 on 2022-10-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0002_remove_accountmt5_level_delete_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.CharField(max_length=20, verbose_name='Fecha Apertura')),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Precio Apertura')),
                ('symbol', models.CharField(max_length=10, verbose_name='Par')),
                ('type', models.CharField(max_length=6, verbose_name='Tipo')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lotaje')),
                ('close_time', models.CharField(max_length=20, verbose_name='Fecha Cierre')),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Precio Cierre')),
                ('commission', models.CharField(max_length=7, verbose_name='Comisiones')),
                ('swap', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Swap')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Beneficio')),
                ('id_account_mt5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps.accountmt5')),
            ],
        ),
    ]
