# Generated by Django 4.1 on 2022-09-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0002_accountmt5_id_client_metaapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmt5',
            name='access_token',
            field=models.CharField(default=1, max_length=50, verbose_name='id DE CUENTA MetaApi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountmt5',
            name='id_client_metaapi',
            field=models.CharField(max_length=50, verbose_name='ID de cuenta MetaApi'),
        ),
    ]
