# Generated by Django 4.1.1 on 2022-10-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0003_accountoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountoperation',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Comisiones'),
        ),
    ]
