# Generated by Django 4.1.1 on 2022-10-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0004_alter_accountoperation_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountoperation',
            name='close_time',
            field=models.DateTimeField(max_length=20, verbose_name='Fecha Cierre'),
        ),
        migrations.AlterField(
            model_name='accountoperation',
            name='open_time',
            field=models.DateTimeField(max_length=20, verbose_name='Fecha Apertura'),
        ),
    ]
