# Generated by Django 4.1 on 2022-09-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0004_alter_accountmt5_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmt5',
            name='access_token',
            field=models.CharField(max_length=100, verbose_name='id DE CUENTA MetaApi'),
        ),
    ]
