# Generated by Django 4.1 on 2022-09-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0005_alter_accountmt5_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmt5',
            old_name='user_account',
            new_name='login',
        ),
    ]
