# Generated by Django 4.1.3 on 2022-12-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0005_alter_accountoperation_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanagement',
            name='end_date',
            field=models.DateTimeField(verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='accountmanagement',
            name='start_date',
            field=models.DateTimeField(verbose_name='Fecha Inicial'),
        ),
    ]
