# Generated by Django 4.1 on 2022-09-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0006_rename_user_account_accountmt5_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanagement',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Comisiones'),
        ),
        migrations.AddField(
            model_name='accountmanagement',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Comisiones'),
        ),
        migrations.AlterField(
            model_name='accountmt5',
            name='access_token',
            field=models.CharField(max_length=100, verbose_name='Token de cuenta MetaApi'),
        ),
    ]
