# Generated by Django 4.1.3 on 2022-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0006_alter_accountmanagement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanagement',
            name='end_date',
            field=models.DateField(verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='accountmanagement',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicial'),
        ),
    ]
