# Generated by Django 4.1.3 on 2022-12-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0007_alter_accountmanagement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountoperation',
            name='open_price',
            field=models.FloatField(verbose_name='Precio Apertura'),
        ),
    ]
