# Generated by Django 4.1 on 2022-09-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0007_accountmanagement_commission_accountmanagement_swap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmt5',
            name='access_token',
        ),
        migrations.AlterField(
            model_name='accountmanagement',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Swap'),
        ),
    ]
