# Generated by Django 4.1.3 on 2022-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0009_alter_accountoperation_close_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountoperation',
            name='close_price',
            field=models.CharField(max_length=10, verbose_name='Precio Cierre'),
        ),
    ]
