# Generated by Django 4.1 on 2022-09-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(max_length=20, verbose_name='Fecha de creación')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('0', 'No Pagado'), ('1', 'Pagado'), ('2', 'Cancelado'), ('3', 'Reembolsado')], max_length=1, verbose_name='Estado')),
                ('transaction_id', models.CharField(max_length=30, verbose_name='ID Transacción')),
            ],
        ),
        migrations.CreateModel(
            name='VpsPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(max_length=20, verbose_name='Fecha de creación')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('0', 'No Pagado'), ('1', 'Pagado'), ('2', 'Cancelado'), ('3', 'Reembolsado')], max_length=1, verbose_name='Estado')),
                ('transaction_id', models.CharField(max_length=30, verbose_name='ID Transacción')),
            ],
        ),
    ]
