# Generated by Django 4.1.1 on 2022-10-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(max_length=20, verbose_name='Fecha de creación')),
                ('expiration', models.DateField(max_length=20, verbose_name='Fecha de creación')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('status', models.CharField(choices=[('Pagar', 'No Pagado'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado'), ('Reembolsado', 'Reembolsado')], max_length=12, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, max_length=30, verbose_name='ID Transacción')),
            ],
        ),
        migrations.CreateModel(
            name='VpsPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(max_length=20, verbose_name='Fecha de creación')),
                ('expiration', models.DateField(max_length=20, verbose_name='Fecha de creación')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('status', models.CharField(choices=[('Pagar', 'No Pagado'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado'), ('Reembolsado', 'Reembolsado')], max_length=12, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, max_length=30, verbose_name='ID Transacción')),
            ],
        ),
    ]
