# Generated by Django 4.1 on 2022-09-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpspayment',
            name='id_account_mt5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps.accountmt5'),
        ),
        migrations.AddField(
            model_name='traderpayment',
            name='id_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vps.accountmanagement'),
        ),
    ]
