# Generated by Django 4.1.1 on 2022-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpspayment',
            name='payment_method',
            field=models.CharField(default='Paypal', max_length=20, verbose_name='Metodo de Pago'),
            preserve_default=False,
        ),
    ]
