# Generated by Django 4.1.1 on 2022-10-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_vpspayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='vpspayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=20, verbose_name='Metodo de Pago'),
        ),
    ]
