# Generated by Django 4.1.2 on 2022-11-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_traderpayment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpayment',
            name='created_date',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='traderpayment',
            name='expiration',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
    ]
