# Generated by Django 4.1.4 on 2023-01-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='due_payments',
            field=models.BooleanField(default=True, verbose_name='¿Tiene pagos vencidos?'),
            preserve_default=False,
        ),
    ]
