# Generated by Django 4.0.6 on 2022-07-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='register_code',
            new_name='validation_code',
        ),
    ]
