# Generated by Django 4.1.1 on 2022-10-14 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, verbose_name='Niveles')),
                ('max_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance Maximo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.level'),
            preserve_default=False,
        ),
    ]
