# Generated by Django 4.1.4 on 2023-01-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_due_payments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
