# Generated by Django 4.1.5 on 2023-01-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_customer_stripe',
            field=models.CharField(default='', max_length=25, verbose_name='ID customer stripe'),
            preserve_default=False,
        ),
    ]
