# Generated by Django 4.1.1 on 2022-10-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='account_level',
        ),
    ]
