# Generated by Django 4.1.5 on 2023-01-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id_customer_stripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_customer_stripe',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ID customer stripe'),
        ),
    ]
