# Generated by Django 4.1.1 on 2022-10-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_level_level_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriber',
            field=models.BooleanField(default=False, verbose_name='Suscriptor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='account_level',
            field=models.CharField(max_length=20, verbose_name='Nivel'),
        ),
    ]
