# Generated by Django 4.1.3 on 2022-12-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_subscriber_alter_level_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='min_balance',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10, verbose_name='Balance Minimo'),
            preserve_default=False,
        ),
    ]
